postio/main/urls.py
from django.urls import path
from .views import HomePageView, AboutUsView, RegulaminView, CreatePackageView, PayPackageView, PackageDetailView, \
    EditPackageView

urlpatterns = [
    path('', HomePageView.as_view(), name='homepage'),
    path('about/', AboutUsView.as_view(), name='about'),
    path('regulamin/', RegulaminView.as_view(), name='regulamin'),
    path('create_package/', CreatePackageView.as_view(), name='create_package'),
    path('pay_package/<int:package_id>/', PayPackageView.as_view(), name='pay_package'),
    path('package_detail/<int:package_id>/', PackageDetailView.as_view(), name='package_detail'),
    path('edit_package/<int:package_id>/', EditPackageView.as_view(), name='edit_package'),
]

postio/postio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('', include("register.urls"))
]

# Obsługa statycznych plików w trybie debugowania
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Dodaj obsługę mediów

postio/main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# model for packages that individual users want to send
class UserPackage(models.Model):
    name = models.CharField(max_length=200) # package name
    weight = models.IntegerField()          # package weight
    width = models.IntegerField()             # package width
    lenght = models.IntegerField()          # package lenght
    height = models.IntegerField()          # package height
    price = models.IntegerField()           # price calculated based upon weight, dimensions
    paid = models.BooleanField()            # check if package delivery was paid for
    package_id = models.AutoField(primary_key=True)  # adds id to package
    status = models.CharField(max_length=50)    # status of package (ready to ship, dispatched, awaiting currier, awaiting pickup, in warehouse, in transit, delivered)
    assigned_courrier = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name='assigned_packages')
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def update_status(self, new_status):
        self.status = new_status
        self.save()
    def __str__(self):
        return (f"Packege id {self.package_id}")
# model of postbox(paczkomat)

# model of deliveryman

postio/main/forms.py
from django import forms
from .models import UserPackage
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.utils.translation import gettext_lazy as _


class UserPackageForm(forms.ModelForm):
    class Meta:
        model = UserPackage
        fields = ['name', 'weight', 'width', 'lenght', 'height']
        labels = {
            'name': 'Nazwa',
            'weight': 'Waga (max 15 kg)',
            'width': 'Szerokość (max 30 cm)',
            'lenght': 'Długość (max 45 cm)',
            'height': 'Wysokość (max 35 cm)',
            'assigned_courier': 'Przypisany kurier',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'weight': forms.NumberInput(attrs={'class': 'form-control'}),
            'width': forms.NumberInput(attrs={'class': 'form-control'}),
            'lenght': forms.NumberInput(attrs={'class': 'form-control'}),
            'height': forms.NumberInput(attrs={'class': 'form-control'}),
            'assigned_courier': forms.Select(attrs={'class': 'form-control'})
        }

    def clean(self):
        cleaned_data = super().clean()
        weight = cleaned_data.get('weight')
        width = cleaned_data.get('width')
        height = cleaned_data.get('height')
        lenght = cleaned_data.get('lenght')

        if weight > 15:
            self.add_error('weight', 'Waga paczki nie może przekraczać 15 kg.')
        if width > 30:
            self.add_error('width', 'Szerokość paczki nie może przekraczać 30 cm.')
        if height > 35:
            self.add_error('height', 'Wysokość paczki nie może przekraczać 35 cm.')
        if lenght > 45:
            self.add_error('lenght', 'Długość paczki nie może przekroczyć 45 cm.')

        return cleaned_data

postio/main/views.py
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, DetailView, View
from .models import UserPackage
from .forms import UserPackageForm
import qrcode
import os
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponseForbidden
from django.views import View
from django.shortcuts import render, redirect



# Create your views here.


class HomePageView(TemplateView):
    template_name = 'main/homepage.html'

    def is_authorized(self, request, *args, **kwargs):
        context = {
            'user_has_permission': request.user.groups.filter(name='Dostawca').exists() or request.user.is_superuser,
        }
        return render(request, 'homepage.html', context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['packages'] = UserPackage.objects.filter(owner=self.request.user)
        return context

class AboutUsView(TemplateView):
    template_name = 'main/about_us.html'


class RegulaminView(TemplateView):
    template_name = 'main/regulamin.html'


class CreatePackageView(CreateView):
    model = UserPackage
    form_class = UserPackageForm
    template_name = 'main/create_package.html'

    def form_valid(self, form):
        package = form.save(commit=False)
        package.owner = self.request.user
        package.price = self.calculate_price(package.weight, package.width, package.height, package.lenght)
        package.paid = False
        package.status = 'ready_to_ship'
        package.save()
        return redirect('pay_package', package_id=package.package_id)

    def calculate_price(self, weight, width, height, length):
        # Calculating package based upon weight, price and dimensions
        base_price = 10
        weight_factor = weight * 0.5
        size_factor = (width * height * length) * 0.01
        return base_price + weight_factor + size_factor


class PayPackageView(View):
    template_name = 'main/pay_package.html'

    def get(self, request, *args, **kwargs):
        package_id = self.kwargs['package_id']
        package = get_object_or_404(UserPackage, pk=package_id)
        context = {'package': package}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        package_id = self.kwargs['package_id']
        package = get_object_or_404(UserPackage, pk=package_id)
        package.paid = True
        package.status = 'paid'
        package.save()
        return redirect('package_detail', package_id=package.package_id)


class PackageDetailView(DetailView):
    model = UserPackage
    template_name = 'main/package_detail.html'
    context_object_name = 'package'
    pk_url_kwarg = 'package_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        package = self.get_object()
        qr_code_path = self.generate_qr_code(package)
        context['qr_code_url'] = qr_code_path
        return context

    def generate_qr_code(self, package):
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        qr.add_data(f'Package ID: {package.package_id}\nStatus: {package.status}\nPrice: {package.price}')
        qr.make(fit=True)

        img = qr.make_image(fill='black', back_color='white')
        qr_code_path = f'media/qr_codes/package_{package.package_id}.png'
        os.makedirs(os.path.dirname(qr_code_path), exist_ok=True)
        img.save(qr_code_path)
        return qr_code_path


class EditPackageView(View):
    template_name = 'main/edit_package.html'

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        package_id = self.kwargs['package_id']
        package = get_object_or_404(UserPackage, pk=package_id)
        form = UserPackageForm(instance=package)
        user_has_permission = request.user.groups.filter(name='Dostawca').exists() or request.user.is_superuser
        if user_has_permission:
            context = {'form': form, 'package': package, 'user_has_permission': user_has_permission}
            return render(request, self.template_name, context)
        else:
            return HttpResponseForbidden("Nie masz pozwolenia żeby edytować tą paczkę.")

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        package_id = self.kwargs['package_id']
        package = get_object_or_404(UserPackage, pk=package_id)
        form = UserPackageForm(request.POST, instance=package)
        user_has_permission = request.user.groups.filter(name='Dostawca').exists() or request.user.is_superuser
        if user_has_permission:
            if form.is_valid():
                form.save()
                return redirect('package_detail', package_id=package.package_id)
            else:
                return render(request, self.template_name,
                              {'form': form, 'package': package, 'user_has_permission': user_has_permission})
        else:
            return HttpResponseForbidden("Nie masz pozwolenia żeby edytować tą paczkę.")

postio/main/templates/main/about_us.html
{% extends "main/homepage.html" %}

{% block content %}
    <div class="container">
        <h1 class="mt-2">O Nas</h1>
        <hr class="mt-0 mb-4">
        <p>Witamy na naszej stronie! Jesteśmy zespołem pasjonatów, którzy ...</p>
    </div>
{% endblock %}

postio/main/templates/main/create_package.html
{% extends "main/homepage.html" %}

{% block content %}
    <div class="container">
        <h1 class="mt-2">Stwórz nową paczkę</h1>
        <hr class="mt-0 mb-4">
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_name">{{ form.name.label }}</label>
                <br>
                {{ form.name }}
                {% if form.name.errors %}
                    <div class="alert alert-danger">
                        {% for error in form.name.errors %}
                            <div>{{ error }}</div>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_weight">{{ form.weight.label }}</label>
                <br>
                {{ form.weight }}
                {% if form.weight.errors %}
                    <div class="alert alert-danger">
                        {% for error in form.weight.errors %}
                            <div>{{ error }}</div>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_width">{{ form.width.label }}</label>
                <br>
                {{ form.width }}
                {% if form.width.errors %}
                    <div class="alert alert-danger">
                        {% for error in form.width.errors %}
                            <div>{{ error }}</div>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_lenght">{{ form.lenght.label }}</label>
                <br>
                {{ form.lenght }}
                {% if form.lenght.errors %}
                    <div class="alert alert-danger">
                        {% for error in form.lenght.errors %}
                            <div>{{ error }}</div>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_height">{{ form.height.label }}</label>
                <br>
                {{ form.height }}
                {% if form.height.errors %}
                    <div class="alert alert-danger">
                        {% for error in form.height.errors %}
                            <div>{{ error }}</div>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <button type="submit" class="btn btn-primary">Stwórz paczkę</button>
        </form>
    </div>
{% endblock %}

postio/main/templates/main/edit_package.html
{% extends 'main/homepage.html' %}


{% block title %}Edycja paczki{% endblock %}

{% block content %}
<div class="container">
    <h1 class="mt-2">Edytuj paczkę</h1>
    <hr class="mt-0 mb-4">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit", class="btn btn-primary">Zapisz</button>
    </form>
</div>
{% endblock %}

postio/main/templates/main/homepage.html
{% load static %}
<!doctype html>
<html>
<head>
    <style type="text/css">
        .sidenav {
            height: 100%;
            width: 250px;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #1b1b1b;
            overflow-x: hidden;
            padding-top: 20px;
        }

        .sidenav a, .dropdown-btn, .sidenav .user-info {
            padding: 6px 8px 6px 16px;
            text-decoration: none;
            font-size: 25px;
            color: #818181;
            display: block;
            border: none;
            background: none;
            width: 100%;
            text-align: left;
            cursor: pointer;
            outline: none;
        }

        .sidenav a:hover, .dropdown-btn:hover, .sidenav .user-info {
            color: #f1f1f1;
        }

        .dropdown-container {
            display: none;
            background-color: #262626;
            padding-left: 8px;
        }

        .main {
            margin-left: 240px;
            padding: 0px 10px;
        }
    </style>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
          crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <title>{% block title %}CoWork Connect Site{% endblock %}</title>
    {% block head_extra %}{% endblock %}</head>
<body>
<div class="sidenav">
    {% if user.is_authenticated %}
    <a href="{% url 'profile' %}">{{ user.username }}</a>
    {% if user_has_permission %}
    <a href="{% url 'edit_package' package_id=1 %}">EDYTUJ PACZKĘ</a>
    {% endif %}
    {% endif %}

    <a href="{% url 'about' %}">O NAS</a>
    <a href="{% url 'regulamin' %}">REGULAMIN</a>

    {% if user.is_authenticated %}
    <a href="{% url 'create_package' %}">NOWA PACZKA</a>

    <a href="{% url 'package_detail' package_id=1 %}">MOJA PACZKA</a>

    <form id="logout-form" action="{% url 'logout' %}" method="post" style="display: none;">
        {% csrf_token %}
    </form>

    <div id="logout-div" style="cursor: pointer;"><a>Wyloguj się</a></div>
    {% else %}
    <div class="user-info">NIE JESTEŚ ZALOGOWANY</div>
    <a href="{% url 'login' %}">LOGOWANIE</a>
    <a href="{% url 'register' %}">REJESTRACJA</a>
    {% endif %}
</div>
<a href="/admin">PANEL ADMINA</a>
<div id="content" class="main">
    <div class="row justify-content-center">
        <div class="col-8">
            <h1 class="mt-2"></h1>
            <hr class="mt=0 mb-4">
            {% block content %}{% endblock %}
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" crossorigin="anonymous"></script>
<script>
    var dropdown = document.getElementsByClassName("dropdown-btn");
    for (var i = 0; i < dropdown.length; i++) {
        dropdown[i].addEventListener("click", function () {
            this.classList.toggle("active");
            var dropdownContent = this.nextElementSibling;
            if (dropdownContent.style.display === "block") {
                dropdownContent.style.display = "none";
            } else {
                dropdownContent.style.display = "block";
            }
        });
    }
</script>
<script>
    $(function () {
        $(".datepicker").datepicker({
            dateFormat: 'yy-mm-dd'
        });
    });
</script>
<script>
    document.getElementById('logout-div').addEventListener('click', function () {
        document.getElementById('logout-form').submit();
    });
</script>
</body>
</html>

postio/main/templates/main/package_detail.html
{% extends "main/homepage.html" %}

{% block content %}
    <div class="container">
        <h1 class="mt-2">Szczegóły Paczki</h1>
        <hr class="mt-0 mb-4">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">ID twojej paczki: {{ package.package_id }}</h5>
                <p class="card-text"><strong>Nazwa:</strong> {{ package.name }}</p>
                <p class="card-text"><strong>Waga:</strong> {{ package.weight }} kg</p>
                <p class="card-text"><strong>Szerokość:</strong> {{ package.width }} cm</p>
                <p class="card-text"><strong>Wysokość:</strong> {{ package.height }} cm</p>
                <p class="card-text"><strong>Długość:</strong> {{ package.lenght }} cm</p>
                <p class="card-text"><strong>Cena:</strong> {{ package.price }} zł</p>
                <p class="card-text"><strong>Status:</strong> {{ package.status }}</p>
                <p class="card-text"><strong>Opłacona:</strong> {{ package.paid|yesno:"Tak,Nie" }}</p>
                <p class="card-text"><strong>Kurier:</strong>{{ package.assigned_courier }}</p>
                <img src="/{{ qr_code_url }}" alt="QR Code">
            </div>
        </div>
    </div>
{% endblock %}

postio/main/templates/main/pay_package.html
{% extends "main/homepage.html" %}


{% block title %}Płatność{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="mt-2">Zapłać za paczkę.</h1>
        <hr class="mt-0 mb-4">
        <p>Paczka: {{ package.name }}</p>
        <p>Cena: {{ package.price }}</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Zapłać</button>
        </form>
    </div>
{% endblock %}

postio/main/templates/main/regulamin.html
{% extends "main/homepage.html" %}

{% block content %}
    <div class="container">
        <h1 class="mt-2">Regulamin</h1>
        <hr class="mt-0 mb-4">
        <p>Witamy w sekcji regulaminu. Prosimy o zapoznanie się z naszymi zasadami...</p>
    </div>
{% endblock %}