postio/main/urls.py
from django.urls import path
from .views import HomePageView, AboutUsView, RegulaminView, CreatePackageView, PayPackageView, PackageDetailView, \
    EditPackageView

urlpatterns = [
    path('', HomePageView.as_view(), name='homepage'),
    path('about/', AboutUsView.as_view(), name='about'),
    path('regulamin/', RegulaminView.as_view(), name='regulamin'),
    path('create_package/', CreatePackageView.as_view(), name='create_package'),
    path('pay_package/<int:package_id>/', PayPackageView.as_view(), name='pay_package'),
    path('package_detail/<int:package_id>/', PackageDetailView.as_view(), name='package_detail'),
    path('edit_package/<int:package_id>/', EditPackageView.as_view(), name='edit_package'),
]

postio/postio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('', include("register.urls"))
]

# Obsługa statycznych plików w trybie debugowania
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Dodaj obsługę mediów

postio/register/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import RegistrationView, CustomLoginView, CustomLogoutView, PasswordChangeAjaxView, ProfileView
from django.conf.urls.static import static
from django.conf import settings
#test commit
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RegistrationView.as_view(), name='register'),
    path('', include("main.urls")),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('register/', RegistrationView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('password_change_ajax/', PasswordChangeAjaxView.as_view, name='password_change_ajax')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postio/register/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.user.username

postio/register/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError


class RegistrationForm(UserCreationForm):
    username = forms.CharField(
        label=_('Użytkownik'),
        help_text=_(
            "Wymagania dla nazwy użytkownika.\nMaksymalnie 150 znaków.\nTylko litery, cyfry i następujące znaki @/./+/-/_."),
        error_messages={
            'required': _('To pole jest wymagane.'),
            'invalid': _('Wprowadź poprawną nazwę użytkownika.'),
            'unique': _('Użytkownik o takiej nazwie już istnieje.')
        }
    )
    first_name = forms.CharField(
        max_length=100,
        label=_('Imię'),
        error_messages={
            'required': _('To pole jest wymagane.'),
        }
    )

    last_name = forms.CharField(
        max_length=100,
        label=_('Nazwisko'),
        error_messages={
            'required': _('To pole jest wymagane.'),
        }
    )

    email = forms.EmailField(
        label=_('Email'),
        error_messages={
            'required': _('To pole jest wymagane.'),
            'invalid': _('Wprowadź poprawny adres email.')
        }
    )

    age = forms.IntegerField(
        label=_('Wiek'),
        error_messages={
            'required': _('To pole jest wymagane.'),
            'invalid': _('Wprowadź poprawny wiek.'),
            'min_value': _('Musisz mieć co najmniej 13 lat.')
        }
    )

    password1 = forms.CharField(
        label=_('Hasło'),
        widget=forms.PasswordInput,
        help_text=_(
            "<ul>"
            "<li>Twoje hasło nie może być podobne do twoich innych danych osobowych.</li>"
            "<li>Twoje hasło musi zawierać co najmniej 8 znaków.</li>"
            "<li>Twoje hasło nie może być powszechnie używane.</li>"
            "<li>Twoje hasło nie może składać się wyłącznie z cyfr.</li>"
            "</ul>"
        ),
        error_messages={
            'required': _("To pole jest wymagane."),
            'password_too_short': _("Hasło jest zbyt krótkie. Powinno zawierać co najmniej 8 znaków."),
            'password_common': _("Hasło jest zbyt powszechne."),
            'password_entirely_numeric': _("Hasło nie może być całkowicie numeryczne."),
        }
    )
    password2 = forms.CharField(
        label=_('Potwierdzenie hasła'),
        widget=forms.PasswordInput,
        help_text=_("Wprowadź to samo hasło, co powyżej, w celu weryfikacji."),
        error_messages={
            'required': _("To pole jest wymagane."),
            'password_mismatch': _("Hasła nie pasują do siebie.")
        }
    )

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'age', 'password1', 'password2']

    def clean_age(self):
        age = self.cleaned_data.get('age')
        if age < 13:
            raise forms.ValidationError(_("Musisz mieć co najmniej 13 lat."))
        return age

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        if password1:
            try:
                validate_password(password1, self.instance)
            except ValidationError as e:
                # Mapowanie komunikatów błędów na kody
                error_messages = {
                    'password_too_short': self.fields['password1'].error_messages.get('password_too_short',
                                                                                      "Hasło jest zbyt krótkie."),
                    'password_too_common': self.fields['password1'].error_messages.get('password_common',
                                                                                       "Hasło jest zbyt powszechne."),
                    'password_entirely_numeric': self.fields['password1'].error_messages.get(
                        'password_entirely_numeric', "Hasło nie może być całkowicie numeryczne."),
                }
                raise forms.ValidationError([error_messages.get(error.code, str(error)) for error in e.error_list])
        return password1
    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.fields['password2'].error_messages['password_mismatch'],
                code='password_mismatch'
            )
        return password2


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class PasswordChangeCustomForm(PasswordChangeForm):
    old_password = forms.CharField(
        label=_('Stare hasło'),
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        error_messages={
            'required': _('To pole jest wymagane.'),
        }
    )
    new_password1 = forms.CharField(
        label=_('Nowe hasło'),
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        help_text=_("Twoje hasło nie może być podobne do twoich innych danych osobowych.\n "
                    "Twoje hasło musi zawierać co najmniej 8 znaków.\n "
                    "Twoje hasło nie może być powszechnie używane. \n"
                    "Twoje hasło nie może składać się wyłącznie z cyfr.\n"),
        error_messages={
            'required': _('To pole jest wymagane.'),
            'password_too_short': _("Hasło jest zbyt krótkie. Powinno zawierać co najmniej 8 znaków."),
            'password_too_common': _("Hasło jest zbyt powszechne."),
            'password_entirely_numeric': _("Hasło nie może być całkowicie numeryczne."),
        }
    )
    new_password2 = forms.CharField(
        label=_('Potwierdź nowe hasło'),
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        help_text=_("Wprowadź to samo hasło, co powyżej, w celu weryfikacji."),
        error_messages={
            'required': _('To pole jest wymagane.'),
            'password_mismatch': _("Hasła nie pasują do siebie."),
        }
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.error_messages.update({
            'password_mismatch': _('Hasła nie pasują do siebie.'),
            'password_incorrect': _('Stare hasło jest niepoprawne.')
        })


    def clean_new_password1(self):
        new_password1 = self.cleaned_data.get('new_password1')
        if new_password1:
            try:
                validate_password(new_password1, self.user)
            except ValidationError as e:
                error_messages = {
                    'password_too_short': self.fields['new_password1'].error_messages['password_too_short'],
                    'password_too_common': self.fields['new_password1'].error_messages['password_too_common'],
                    'password_entirely_numeric': self.fields['new_password1'].error_messages['password_entirely_numeric'],
                }
                raise forms.ValidationError([error_messages[error.code] for error in e.error_list])
        return new_password1


    def clean_new_password2(self):
        new_password1 = self.cleaned_data.get('new_password1')
        new_password2 = self.cleaned_data.get('new_password2')
        if new_password1 and new_password2 and new_password1 != new_password2:
            raise forms.ValidationError(
                self.fields['new_password2'].error_messages['password_mismatch'],
                code='password_mismatch'
            )
        return new_password2


    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.user.check_password(old_password):
            raise forms.ValidationError(
                self.error_messages['password_incorrect'],
                code='password_incorrect',
            )
        return old_password

postio/register/views.py
from .forms import RegistrationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, DetailView, View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponseForbidden, JsonResponse
from django.views import View
from django.shortcuts import render, redirect
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from .forms import UserForm, PasswordChangeCustomForm
from django.contrib.auth import login


class RegistrationView(CreateView):
    form_class = RegistrationForm
    template_name = 'register/register.html'
    success_url = reverse_lazy('homepage')

    def form_valid(self, form):
        response = super().form_valid(form)
        user = form.save()
        login(self.request, user)
        # user_email = form.cleaned_data.get('email')
        # send_mail(
        #     "Rejestracja w serwisei Post-Io.",
        #     'Dziękujemy za rejestrację w naszym serwisie.',
        #     settings.EMAIL_HOST_USER,
        #     [user_email],
        #     fail_silently=False,
        # )
        return response


class CustomLoginView(LoginView):
    template_name = 'register/login.html'
    success_url = reverse_lazy('homepage')


class CustomLogoutView(LogoutView):
    next_page = reverse_lazy('homepage')



class ProfileView(LoginRequiredMixin, View):
    template_name = 'register/profile.html'

    def get(self, request, *args, **kwargs):
        user_form = UserForm(instance=request.user)
        password_form = PasswordChangeCustomForm(user=request.user)

        return render(request, self.template_name, {
            'user_form': user_form,
            'password_form': password_form
        })

    def post(self, request, *args, **kwargs):
        user_form = UserForm(request.POST, instance=request.user)
        password_form = PasswordChangeCustomForm(user=request.user, data=request.POST)

        if 'username' in request.POST:
            if user_form.is_valid():
                user_form.save()
                messages.success(request, 'Profil został zaktualizowany pomyślnie.')
                return redirect('profile')

        if 'old_password' in request.POST:
            if password_form.is_valid():
                user = password_form.save()
                update_session_auth_hash(request, user)
                messages.success(request, 'Hasło zostało zmienione pomyślnie.')
                return redirect('profile')
            else:
                messages.error(request, "Wystąpił błąd. Proszę spróbuj ponownie.")

        return render(request, self.template_name, {
            'user_form': user_form,
            'password_form': password_form
        })


class PasswordChangeAjaxView(View):
    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return JsonResponse({'status': 'ok'}, status=200)
            #         else:
            return JsonResponse({'status': 'error', 'errors': 'form.errors'}, status=400)

postio/register/templates/register/login.html
{% extends "main/homepage.html" %}
<style>
    .custom-input {
        height: 50px;
        width: 620px;
        box-sizing: border-box; /* Uwzględnia padding i obramowanie */
    }

    .custom-input-group {
        display: flex;
        align-items: center;
    }
</style>
{% block title %}
    Logowanie
{% endblock %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_username">Użytkownik</label>
            <br>
            <input type="text" class="custom-input" name="username" id="id_username">
        </div>
        <div class="form-group">
            <label for="id_password">Hasło</label>
            <div class="input-group custom-input-group">
                <input type="password" class="custom-input" name="password" id="id_password">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="togglePassword">Pokaż</button>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-success" style="margin-bottom: 20px">Zaloguj się</button>
        <p>Nie masz konta? Stwórz je <a href="{% url 'register' %}">tutaj</a>.</p>
    </form>

    <script>
        document.getElementById('togglePassword').addEventListener('click', function () {
            var passwordField = document.getElementById('id_password');
            var type = passwordField.getAttribute('type') === 'password' ? 'text' : 'password';
            passwordField.setAttribute('type', type);
            this.textContent = type === 'password' ? 'Pokaż' : 'Ukryj';
        });
    </script>
{% endblock %}

postio/register/templates/register/profile.html
{% extends "main/homepage.html" %}

{% block title %}
Konto Użytkownika
{% endblock %}

<!Dostype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profil użytkownika</title>
    <style>
        .password-container {
        position: relative;
        display: inline-block;
        margin-bottom: 10px;
        }

        .password-container button {
        position: absolute;
        right: 10px;
        top: 50%;
        transform: translateY(-50%);
        cursor:pointer;
        background-color: #f0f0f0;
        border: none;
        padding: 5px 10px;
        }

        .password-container input[type="password"],
        .password-container input[type="text"] {
            padding-right: 60px;
        }
    </style>
</head>

{% block content %}
<h2>Profil użytkownika <br> {{ user.username }}</h2>
<form method="post" class="form-group">
    {% csrf_token %}
    <div class="form-group">
        <label>Użytkownik</label>
        <br>
        <p><input type="text" name="username" value="{{ user.username }}"></p>
        {{ user_form.username.help_text|safe }}
        {{ user_form.username.errors }}
    </div>
    <div class="form-group">
        <label>Imię</label>
        <br>
        {{ user_form.first_name }}
        {{ user_form.first_name.errors }}
    </div>
    <div class="form-group">
        <label>Nazwisko</label>
        <br>
        {{ user_form.last_name }}
        {{ user_form.last_name.errors }}
    </div>
    <div class="form-group">
        <label>Adres email</label>
        <br>
        {{ user_form.email }}
        {{ user_form.email.errors }}
    </div>
    <button type="submit" class="btn btn-primary">Zapisz zmiany</button>
</form>
<br>
<h3>Zmień hasło</h3>
<form method="post" id="passwordChangeForm" class="form-group">
    {% csrf_token %}
    <div class="form-group">
        <label>Stare Hasło</label>
        <br>
        <div class="input-group">
            {{ password_form.old_password }}
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="toggleOldPassword">Pokaż</button>
            </div>
        </div>
        {{ password_form.old_password.errors }}
    </div>
    <div class="form-group">
        <label>Nowe hasło</label>
        <br>
        <div class="input-group">
            <input type="password" name="new_password1" required id="id_new_password1" autocomplete="new-password">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="toggleNewPassword1">Pokaż</button>
            </div>
        </div>
        {{ password_form.new_password1.help_text|safe }}
        {{ password_form.new_password1.errors }}
    </div>
    <div class="form-group">
        <label>Powtórz hasło</label>
        <br>
        <div class="input-group">
            <input type="password" name="new_password2" required id="id_new_password2" autocomplete="new-password">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="toggleNewPassword2">Pokaż</button>
            </div>
        </div>
        {{ password_form.new_password2.help_text|safe }}
        {{ password_form.new_password2.errors }}
    </div>
    <button type="submit" class="btn btn-primary">Zmień hasło</button>
</form>

{% endblock %}

{% block script %}
<script>
    function togglePasswordVisibility(passwordFieldId, toggleButton) {
        var passwordInput = document.getElementById(passwordFieldId);
        if (passwordInput.type === 'password') {
            passwordInput.type = 'text';
            toggleButton.textContent = 'Ukryj';
        } else {
            passwordInput.type = 'password';
            toggleButton.textContent = 'Pokaż';
        }
    }
</script>
{% endblock %}

postio/register/templates/register/register.html
{% extends "main/homepage.html" %}

{% block title %}
    Stwórz konto
{% endblock %}

{% block content %}
    <form method="POST" class="form-group">
        {% csrf_token %}
        <div class="form-group">
            <label>Użytkownik</label>
            <br>
            {{ form.username }}
            <br>
            {{ form.username.help_text|safe }}
            {{ form.username.errors }}
        </div>
        <div class="form-group">
            <label>Imię</label>
            <br>
            {{ form.first_name }}
            {{ form.first_name.errors }}
        </div>
        <div class="form-group">
            <label>Nazwisko</label>
            <br>
            {{ form.last_name }}
            {{ form.last_name.errors }}
        </div>
        <div class="form-group">
            <label>Adres email</label>
            <br>
            {{ form.email }}
            {{ form.email.errors }}
        </div>
        <div class="form-group">
            <label>Wiek</label>
            <br>
            {{ form.age }}
            {{ form.age.errors }}
        </div>
        <div class="form-group">
            <label>Hasło</label>
            <br>
            <div class="input-group">
                {{ form.password1 }}
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="togglePassword1">Pokaż</button>
                </div>
            </div>
            {{ form.password1.help_text|safe }}

        </div>
        <div class="form-group">
            <label>Powtórz hasło</label>
            <br>
            <div class="input-group">
                {{ form.password2 }}
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="togglePassword2">Pokaż</button>
                </div>
            </div>
            {{ form.password2.help_text|safe }}
            {{ form.password2.errors }}
        </div>
        <h5>Pamiętaj, że zakładając konto zgadzasz się na warunki naszego <a href="{% url 'regulamin' %}">regulaminu</a>.</h5>
        <button type="submit" class="btn btn-success" style="margin-top: 20px">Zarejestruj się</button>
    </form>

    <script>
        document.getElementById('togglePassword1').addEventListener('click', function () {
            var passwordField1 = document.getElementById('id_password1');
            var type1 = passwordField1.getAttribute('type') === 'password' ? 'text' : 'password';
            passwordField1.setAttribute('type', type1);
            this.textContent = type1 === 'password' ? 'Pokaż' : 'Ukryj';
        });

        document.getElementById('togglePassword2').addEventListener('click', function () {
            var passwordField2 = document.getElementById('id_password2');
            var type2 = passwordField2.getAttribute('type') === 'password' ? 'text' : 'password';
            passwordField2.setAttribute('type', type2);
            this.textContent = type2 === 'password' ? 'Pokaż' : 'Ukryj';
        });
    </script>
{% endblock %}